defmodule Predicates.LTreeTest do
  use Predicates.DataCase, async: true
  import Assertions

  alias Predicates.PredicateConverter, as: Converter
  alias Predicates.PredicateError

  defmodule Node do
    @moduledoc false
    use Ecto.Schema

    schema "pred_nodes" do
      field :name, :string
      field :path, Predicates.Test.LTree
    end

    def migrate do
      """
      CREATE TABLE #{:pred_nodes} (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name text,
        path ltree
      )
      """
    end
  end

  setup do
    Predicates.Repo.query!(Node.migrate(), [])

    Predicates.Repo.insert_all(Node, [
      %{name: "root", path: "a"},
      %{name: "child", path: "a.b"},
      %{name: "grandchild", path: "a.b.c"},
      %{name: "other", path: "x.y"},
      %{name: "none", path: nil}
    ])

    :ok
  end

  defp names(predicate) do
    Converter.build_query(Node, predicate)
    |> Predicates.Repo.all()
    |> Enum.map(& &1.name)
  end

  describe "existing operators" do
    test "eq & not_eq" do
      assert ["child"] = names(%{"op" => "eq", "path" => "path", "arg" => "a.b"})
      assert ["none"] = names(%{"op" => "eq", "path" => "path", "arg" => nil})

      assert_lists_equal ["root", "grandchild", "other", "none"],
                         names(%{"op" => "not_eq", "path" => "path", "arg" => "a.b"})
    end

    test "in & not_in" do
      assert_lists_equal ["root", "other"],
                         names(%{"op" => "in", "path" => "path", "arg" => ["a", "x.y"]})

      assert_lists_equal ["root", "none"],
                         names(%{"op" => "in", "path" => "path", "arg" => ["a", nil]})

      assert_lists_equal ["child", "grandchild", "none"],
                         names(%{"op" => "not_in", "path" => "path", "arg" => ["a", "x.y"]})
    end

    test "gt & lt" do
      assert_lists_equal ["child", "grandchild", "other"],
                         names(%{"op" => "gt", "path" => "path", "arg" => "a"})

      assert ["root"] = names(%{"op" => "lt", "path" => "path", "arg" => "a.b"})
    end

    test "string operators" do
      assert_lists_equal ["child", "grandchild"],
                         names(%{"op" => "starts_with", "path" => "path", "arg" => "a.b"})

      assert ["grandchild"] = names(%{"op" => "ends_with", "path" => "path", "arg" => ".c"})

      assert_lists_equal ["child", "grandchild"],
                         names(%{"op" => "like", "path" => "path", "arg" => ".b"})

      assert ["other"] = names(%{"op" => "ilike", "path" => "path", "arg" => "X.Y"})
      assert ["other"] = names(%{"op" => "contains", "path" => "path", "arg" => "y"})
    end
  end

  describe "hierarchy operators" do
    test "descendant_of" do
      assert_lists_equal ["child", "grandchild"],
                         names(%{"op" => "descendant_of", "path" => "path", "arg" => "a.b"})

      assert_lists_equal ["grandchild", "other"],
                         names(%{
                           "op" => "descendant_of",
                           "path" => "path",
                           "arg" => ["a.b.c", "x"]
                         })

      assert [] = names(%{"op" => "descendant_of", "path" => "path", "arg" => []})
    end

    test "ancestor_of" do
      assert_lists_equal ["root", "child"],
                         names(%{"op" => "ancestor_of", "path" => "path", "arg" => "a.b"})

      assert_lists_equal ["root", "child", "other"],
                         names(%{
                           "op" => "ancestor_of",
                           "path" => "path",
                           "arg" => ["a.b", "x.y.z"]
                         })
    end

    test "lquery" do
      assert_lists_equal ["child", "grandchild"],
                         names(%{"op" => "lquery", "path" => "path", "arg" => "*.b.*"})

      assert_lists_equal ["root", "other"],
                         names(%{"op" => "lquery", "path" => "path", "arg" => ["a", "x.*"]})
    end

    test "can be combined with other predicates" do
      assert ["grandchild"] =
               names(%{
                 "op" => "and",
                 "args" => [
                   %{"op" => "descendant_of", "path" => "path", "arg" => "a"},
                   %{
                     "op" => "not",
                     "arg" => %{"op" => "ancestor_of", "path" => "path", "arg" => "a.b"}
                   }
                 ]
               })
    end

    test "fail on non-ltree fields" do
      for op <- ["descendant_of", "ancestor_of", "lquery"] do
        assert_raise PredicateError, ~r/not supported/, fn ->
          Converter.build_query(Node, %{"op" => op, "path" => "name", "arg" => "a"})
        end
      end
    end

    test "fail on non-string arguments" do
      for op <- ["descendant_of", "ancestor_of", "lquery"], arg <- [nil, 1, true, ["a", nil]] do
        assert_raise PredicateError, ~r/required to be a string/, fn ->
          Converter.build_query(Node, %{"op" => op, "path" => "path", "arg" => arg})
        end
      end
    end
  end
end

defmodule Predicates.LTreeConfigTest do
  # Modifies application env, so it can't run async.
  use ExUnit.Case, async: false

  alias Predicates.SchemaHelpers

  defmodule ConfiguredNode do
    @moduledoc false
    use Ecto.Schema

    schema "pred_configured_nodes" do
      field :path, Predicates.Test.ConfiguredLTree
      field :auto_path, Predicates.Test.LTree
      field :name, :string
    end
  end

  test "detects ltree types listed in the :ltree_types config" do
    refute SchemaHelpers.ltree_field?(ConfiguredNode, :path)

    Application.put_env(:ecto_predicates, :ltree_types, [Predicates.Test.ConfiguredLTree])
    on_exit(fn -> Application.delete_env(:ecto_predicates, :ltree_types) end)

    assert SchemaHelpers.ltree_field?(ConfiguredNode, :path)
  end

  test "auto-detects Ecto types with type/0 returning :ltree" do
    assert SchemaHelpers.ltree_field?(ConfiguredNode, :auto_path)
    refute SchemaHelpers.ltree_field?(ConfiguredNode, :name)
  end
end
