services:
  db:
          image: postgres:14.4-alpine
          restart: unless-stopped
          environment:
              POSTGRES_USER: ${DB_USER}
              POSTGRES_PASSWORD: ${DB_PASSWORD}
              POSTGRES_DB: ${DB_DATABASE}
          ports:
              - "${DB_PORT-5432}:5432"
          healthcheck:
              test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
              interval: 10s
              timeout: 3s
              start_period: 30s
              start_interval: 1s
