name: 🔩 Publish Release (Auto)

on:
    push:
        branches:
            - main
        paths:
            - "mix.exs"
    # Until this is proven, allow manual triggers
    workflow_dispatch:

jobs:
    release:
        name: Publish Release
        if: github.ref == 'refs/heads/main'
        uses: box-id/github-actions-oss/.github/workflows/elixir_publish_release.yml@main
        permissions:
            contents: write
            id-token: write
            pull-requests: read
            issues: read
        with:
            version-prefix: ""
