name: 👉 Trigger Version Bump

on:
    workflow_dispatch:

jobs:
    create_version_bump_pr:
        name: Create Version Bump PR
        if: github.ref == 'refs/heads/main'
        uses: box-id/github-actions-oss/.github/workflows/elixir_version_bump.yml@main
        permissions:
            contents: write
            pull-requests: write
            actions: read
        with:
            version-prefix: ""
